import { useState, type FormEvent } from 'react';
import { useGetUsersQuery, useCreateUserMutation, useUpdateUserStatusMutation } from '../../redux/features/users/usersApi';
import { Search, UserPlus, Power, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router';

export default function AdminOperatorsPage() {
    const navigate = useNavigate(); const [search,setSearch]=useState(''); const [createOpen,setCreateOpen]=useState(false);
    const {data,isFetching,refetch}=useGetUsersQuery({page:1,limit:50,search,role:'OPERATOR'}); const [createUser,{isLoading:creating}]=useCreateUserMutation(); const [setStatus]=useUpdateUserStatusMutation();
    const [form,setForm]=useState({name:'',email:'',password:''});
    const submit=async(e:FormEvent)=>{e.preventDefault(); await createUser({...form,role:'OPERATOR'}).unwrap(); setForm({name:'',email:'',password:''});setCreateOpen(false);refetch();};
    return <div className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-7xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><button onClick={()=>navigate('/admin/dashboard')} className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={17}/> Admin Dashboard</button><button onClick={()=>setCreateOpen(v=>!v)} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold"><UserPlus size={17}/> Add Operator</button></div><div className="rounded-2xl bg-surface p-5 shadow-sm"><h1 className="text-xl font-bold">Operators</h1><div className="mt-4 flex items-center gap-2 rounded-lg border border-surface-border px-3"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or email" className="w-full bg-transparent py-3 text-sm outline-none"/></div>{createOpen&&<form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-surface-border p-4 sm:grid-cols-4"><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-lg border border-surface-border px-3 py-2.5"/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded-lg border border-surface-border px-3 py-2.5"/><input required minLength={8} type="password" placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="rounded-lg border border-surface-border px-3 py-2.5"/><button disabled={creating} className="rounded-lg bg-primary px-4 py-2 font-semibold">{creating?'Creating…':'Create Operator'}</button></form>}
            <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-surface-border text-text-secondary"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Status</th><th className="p-3">Last Login</th><th className="p-3">Action</th></tr></thead><tbody>{data?.users.map(u=><tr key={u.id} className="border-b border-surface-border"><td className="p-3 font-semibold">{u.name}</td><td className="p-3">{u.email}</td><td className="p-3">{u.status}</td><td className="p-3">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'Never'}</td><td className="p-3"><button onClick={()=>setStatus({id:u.id,status:u.status==='ACTIVE'?'INACTIVE':'ACTIVE'}).unwrap()} className="flex items-center gap-1 rounded-lg border border-surface-border px-3 py-1.5"><Power size={15}/>{u.status==='ACTIVE'?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table>{isFetching&&<p className="p-4 text-sm text-text-secondary">Loading…</p>}{!isFetching&&!data?.users.length&&<p className="p-6 text-center text-sm text-text-secondary">No operators found.</p>}</div></div></div></div>;
}
